---@class WorldObject
--- Visuals
---@field setModel fun(self: WorldObject, modelPath: modelPath)
---@field getModel fun(self: WorldObject): modelPath
---@field setScales fun(self: WorldObject, scaleX: scale?, scaleY: scale?, scaleZ: scale?)
---@field getScales fun(self: WorldObject): scaleX: scale, scaleY: scale, scaleZ: scale
--- Position and Movement
---@field setFacingAngles fun(self: WorldObject, xyAngle: radians?, xyzAngle: radians?)
---@field getFacingAngles fun(self: WorldObject): xyAngle: radians, xyzAngle: radians
---@field setPosition fun(self: WorldObject, x: coordinate?, y: coordinate?, z: coordinate?)
---@field getPosition fun(self: WorldObject): x: coordinate, y: coordinate, z: coordinate
--- Animation
---@field animate fun(self: WorldObject, animation: Animation)