if Debug then Debug.beginFile "TotalControl/Adapter/Warcraft3/Natives/UnitNatives" end
OnInit.module("TotalControl/Adapter/Warcraft3/Natives/UnitNatives", function(require)
    ---@class UnitNatives
    local UnitNatives = {
        Property = {
            Weapon = { Field = {} },
            Field = {}
        },
        Type = {},
        Hero = {},
        Building = {
            GoldMine = {},
            Waygate = {},
            UnitShop = {},
            ItemShop = {}
        },
        Item = {},
        Ability = {},
        Buff = {},
        Order = { NoAI = {} },
        PropertyField = {}
    }

    UnitNatives.Create = CreateUnit
    UnitNatives.CreateWithSkin = BlzCreateUnitWithSkin
    UnitNatives.CreateByName = CreateUnitByName
    UnitNatives.CreateAtLocation = CreateUnitAtLoc
    UnitNatives.CreateAtLocationByName = CreateUnitAtLocByName
    UnitNatives.CreateCorpse = CreateCorpse
    UnitNatives.Kill = KillUnit
    UnitNatives.Destroy = RemoveUnit
    UnitNatives.Equals = IsUnit
    UnitNatives.Show = ShowUnit
    UnitNatives.SetPosition = SetUnitPosition
    UnitNatives.SetLocation = SetUnitPositionLoc
    UnitNatives.GetLocation = GetUnitLoc
    UnitNatives.SetX = SetUnitX
    UnitNatives.GetX = GetUnitX
    UnitNatives.SetY = SetUnitY
    UnitNatives.GetY = GetUnitY
    UnitNatives.GetZ = BlzGetLocalUnitZ -- same as BlzGetUnitZ
    UnitNatives.SetOrientation = SetUnitFacing
    UnitNatives.SetOrientationTimed = SetUnitFacingTimed
    UnitNatives.SetOrientationEx = BlzSetUnitFacingEx
    UnitNatives.GetOrientation = GetUnitFacing
    UnitNatives.IsInRange = IsUnitInRangeXY
    UnitNatives.IsInRangeOfUnit = IsUnitInRange
    UnitNatives.IsInRangeOfLocation = IsUnitInRangeLoc
    UnitNatives.IsVisible =
    IsUnitVisible                         -- as insane as this sounds, I think Visible is not necessarily a reverse of IsInvisible....
    UnitNatives.IsInFog = IsUnitFogged
    UnitNatives.IsInBlackMask = IsUnitMasked
    UnitNatives.IsInTransport = IsUnitInTransport
    UnitNatives.IsTransported = IsUnitLoaded
    UnitNatives.SetAnimation = SetUnitAnimation
    UnitNatives.GetAnimation = BlzGetAnimName
    UnitNatives.SetAnimationByIndex = SetUnitAnimationByIndex
    UnitNatives.SetAnimationWithRarity = SetUnitAnimationWithRarity
    UnitNatives.SetAnimationProperty = AddUnitAnimationProperties
    UnitNatives.QueueAnimation = QueueUnitAnimation
    UnitNatives.RotateModelPartTowards = SetUnitLookAt
    UnitNatives.ResetModelPart = ResetUnitLookAt
    UnitNatives.Pause = PauseUnit
    UnitNatives.PauseEx = BlzPauseUnitEx
    UnitNatives.IsPaused = IsUnitPaused
    UnitNatives.GetRallyLocation = GetUnitRallyPoint
    UnitNatives.GetRallyUnit = GetUnitRallyUnit
    UnitNatives.GetRallyDestructable = GetUnitRallyDestructable
    UnitNatives.ShareVision = UnitShareVision
    UnitNatives.SuspendDecay = UnitSuspendDecay
    UnitNatives.ResetCooldown = UnitResetCooldown -- ???
    UnitNatives.DamagePoint = UnitDamagePoint
    UnitNatives.DamageTarget = UnitDamageTarget
    UnitNatives.InterruptAttack = BlzUnitInterruptAttack

    UnitNatives.Property.SetState = SetUnitState
    UnitNatives.Property.GetState = GetUnitState
    UnitNatives.Property.SetMaxHealth = BlzSetUnitMaxHP
    UnitNatives.Property.GetMaxHealth = BlzGetUnitMaxHP
    UnitNatives.Property.SetMaxMana = BlzSetUnitMaxMana
    UnitNatives.Property.GetMaxMana = BlzGetUnitMaxMana
    UnitNatives.Property.UseAltIcon = UnitSetUsesAltIcon
    UnitNatives.Property.AddClass = UnitAddType
    UnitNatives.Property.RemoveClass = UnitRemoveType
    UnitNatives.Property.IgnoreAlarm = UnitIgnoreAlarm
    UnitNatives.Property.ToggleIgnoreAlarm = UnitIgnoreAlarmToggled
    UnitNatives.Property.SetName = BlzSetUnitName
    UnitNatives.Property.GetName = GetUnitName
    UnitNatives.Property.GetFoodUsed = GetUnitFoodUsed
    UnitNatives.Property.GetFoodMade = GetUnitFoodMade
    UnitNatives.Property.UseFood = SetUnitUseFood
    UnitNatives.Property.AbideByPathing = SetUnitPathing
    UnitNatives.Property.GetPointValue = GetUnitPointValue
    UnitNatives.Property.SetCustomValue = SetUnitUserData
    UnitNatives.Property.GetCustomValue = GetUnitUserData
    UnitNatives.Property.GetType = GetUnitTypeId
    UnitNatives.Property.IsOfClass = IsUnitType
    UnitNatives.Property.GetRace = GetUnitRace
    UnitNatives.Property.IsOfRace = IsUnitRace
    UnitNatives.Property.SetRescuable = SetUnitRescuable
    UnitNatives.Property.SetRescueRange = SetUnitRescueRange
    UnitNatives.Property.SetExplodable = SetUnitExploded
    UnitNatives.Property.SetInvulnerable = SetUnitInvulnerable
    UnitNatives.Property.SetMovementSpeed = SetUnitMoveSpeed
    UnitNatives.Property.GetMovementSpeed = GetUnitMoveSpeed
    UnitNatives.Property.GetDefaultMovementSpeed = GetUnitDefaultMoveSpeed
    UnitNatives.Property.SetMovementType = BlzSetUnitMovementType
    UnitNatives.Property.GetMovementType = BlzGetUnitMovementType
    UnitNatives.Property.SetFlyingHeight = SetUnitFlyHeight
    UnitNatives.Property.GetFlyingHeight = GetUnitFlyHeight
    UnitNatives.Property.GetDefaultFlyingHeight = GetUnitDefaultFlyHeight
    UnitNatives.Property.SetRotationSpeed = SetUnitTurnSpeed
    UnitNatives.Property.GetRotationSpeed = GetUnitTurnSpeed
    UnitNatives.Property.GetDefaultRotationSpeed = GetUnitDefaultTurnSpeed
    UnitNatives.Property.SetPropWindow = SetUnitPropWindow
    UnitNatives.Property.GetPropWindow = GetUnitPropWindow
    UnitNatives.Property.GetDefaultPropWindow = GetUnitDefaultPropWindow
    UnitNatives.Property.SetTargetAcquisitionRange = SetUnitAcquireRange
    UnitNatives.Property.GetTargetAcquisitionRange = GetUnitAcquireRange
    UnitNatives.Property.GetDefaultTargetAcquisitionRange = GetUnitDefaultAcquireRange
    UnitNatives.Property.SetCreepGuard = SetUnitCreepGuard
    UnitNatives.Property.SetOwner = SetUnitOwner
    UnitNatives.Property.GetOwner = GetOwningPlayer
    UnitNatives.Property.IsOwnedBy = IsUnitOwnedByPlayer
    UnitNatives.Property.IsAlly = IsUnitAlly
    UnitNatives.Property.IsEnemy = IsUnitEnemy
    UnitNatives.Property.IsInvisible = IsUnitInvisible
    UnitNatives.Property.IsSelected = IsUnitSelected
    UnitNatives.Property.IsSelectable = BlzIsUnitSelectable
    UnitNatives.Property.Select = SelectUnit
    UnitNatives.Property.ClearSelection = ClearSelection
    UnitNatives.Property.IsHidden = IsUnitHidden
    UnitNatives.Property.IsDetected = IsUnitDetected
    UnitNatives.Property.IsIllusion = IsUnitIllusion
    UnitNatives.Property.IsInvulnerable = BlzIsUnitInvulnerable
    UnitNatives.Property.SetArmor = BlzSetUnitArmor
    UnitNatives.Property.GetArmor = BlzGetUnitArmor
    UnitNatives.Property.GetArmorType = BlzGetUnitArmorType
    UnitNatives.Property.GetCollisionSize = BlzGetUnitCollisionSize
    UnitNatives.Property.SetTeamColor = SetUnitColor
    UnitNatives.Property.ShowTeamGlow = BlzShowUnitTeamGlow
    UnitNatives.Property.SetScale = SetUnitScale
    UnitNatives.Property.SetTimeScale = SetUnitTimeScale
    UnitNatives.Property.SetBlendTime = SetUnitBlendTime
    UnitNatives.Property.SetColor = SetUnitVertexColor
    UnitNatives.Property.SetSkin = BlzSetUnitSkin
    UnitNatives.Property.GetSkin = BlzGetUnitSkin
    UnitNatives.Property.IsAlive = UnitAlive

    UnitNatives.Property.Weapon.SetBaseDamage = BlzSetUnitBaseDamage
    UnitNatives.Property.Weapon.GetBaseDamage = BlzGetUnitBaseDamage
    UnitNatives.Property.Weapon.SetDiceAmount = BlzSetUnitDiceNumber
    UnitNatives.Property.Weapon.GetDiceAmount = BlzGetUnitDiceNumber
    UnitNatives.Property.Weapon.SetDiceSides = BlzSetUnitDiceSides
    UnitNatives.Property.Weapon.GetDiceSides = BlzGetUnitDiceSides
    UnitNatives.Property.Weapon.SetCooldown = BlzSetUnitAttackCooldown
    UnitNatives.Property.Weapon.GetCooldown = BlzGetUnitAttackCooldown

    UnitNatives.Property.Weapon.Field.SetBoolean = BlzSetUnitWeaponBooleanField
    UnitNatives.Property.Weapon.Field.GetBoolean = BlzGetUnitWeaponBooleanField
    UnitNatives.Property.Weapon.Field.SetInteger = BlzSetUnitWeaponIntegerField
    UnitNatives.Property.Weapon.Field.GetInteger = BlzGetUnitWeaponIntegerField
    UnitNatives.Property.Weapon.Field.SetReal = BlzSetUnitWeaponRealField
    UnitNatives.Property.Weapon.Field.GetReal = BlzGetUnitWeaponRealField
    UnitNatives.Property.Weapon.Field.SetString = BlzSetUnitWeaponStringField
    UnitNatives.Property.Weapon.Field.GetString = BlzGetUnitWeaponStringField

    UnitNatives.Property.Field.SetBoolean = BlzSetUnitBooleanField
    UnitNatives.Property.Field.GetBoolean = BlzGetUnitBooleanField
    UnitNatives.Property.Field.SetInteger = BlzSetUnitIntegerField
    UnitNatives.Property.Field.GetInteger = BlzGetUnitIntegerField
    UnitNatives.Property.Field.SetReal = BlzSetUnitRealField
    UnitNatives.Property.Field.GetReal = BlzGetUnitRealField
    UnitNatives.Property.Field.SetString = BlzSetUnitStringField
    UnitNatives.Property.Field.GetString = BlzGetUnitStringField

    UnitNatives.Type.GetPointValue = GetUnitPointValueByType
    UnitNatives.Type.GetFoodUsed = GetFoodUsed
    UnitNatives.Type.GetFoodMade = GetFoodMade
    UnitNatives.Type.IsHero = IsHeroUnitId
    UnitNatives.Type.IsOfClass = IsUnitIdType
    UnitNatives.Type.GetGoldCost = GetUnitGoldCost
    UnitNatives.Type.GetLumberCost = GetUnitWoodCost
    UnitNatives.Type.GetBuildTime = GetUnitBuildTime

    UnitNatives.Hero.SetStrength = SetHeroStr
    UnitNatives.Hero.GetStrength = GetHeroStr
    UnitNatives.Hero.SetAgility = SetHeroAgi
    UnitNatives.Hero.GetAgility = GetHeroAgi
    UnitNatives.Hero.SetIntelligence = SetHeroInt
    UnitNatives.Hero.GetIntelligence = GetHeroInt
    UnitNatives.Hero.SetExp = SetHeroXP
    UnitNatives.Hero.AddExp = AddHeroXP
    UnitNatives.Hero.GetExp = GetHeroXP
    UnitNatives.Hero.SetStat = BlzSetHeroStatEx
    UnitNatives.Hero.GetStat = BlzGetHeroStat
    UnitNatives.Hero.SetPrimaryStatAmount = BlzSetHeroPrimaryStat
    UnitNatives.Hero.GetPrimaryStat = BlzGetHeroPrimaryStat
    UnitNatives.Hero.SuspendExpGain = SuspendHeroXP
    UnitNatives.Hero.IsExpGainSuspended = IsSuspendedXP
    UnitNatives.Hero.SetLevel = SetHeroLevel
    UnitNatives.Hero.ReduceLevels = UnitStripHeroLevel
    UnitNatives.Hero.GetLevel = GetHeroLevel
    UnitNatives.Hero.GetSkillPoints = GetHeroSkillPoints
    UnitNatives.Hero.ChangeSkillPoints = UnitModifySkillPoints
    UnitNatives.Hero.LearnSkill = SelectHeroSkill
    UnitNatives.Hero.UnlearnSkill = BlzDeleteHeroAbility
    UnitNatives.Hero.SetName = BlzSetHeroProperName
    UnitNatives.Hero.GetName = GetHeroProperName
    UnitNatives.Hero.Revive = ReviveHero
    UnitNatives.Hero.ReviveAtLocation = ReviveHeroLoc

    UnitNatives.Item.Add = UnitAddItem
    UnitNatives.Item.AddById = UnitAddItemById
    UnitNatives.Item.AddToSlotById = UnitAddItemToSlotById
    UnitNatives.Item.Remove = UnitRemoveItem
    UnitNatives.Item.RemoveFromSlot = UnitRemoveItemFromSlot
    UnitNatives.Item.Has = UnitHasItem
    UnitNatives.Item.GetAtSlot = UnitItemInSlot
    UnitNatives.Item.GetInventorySize = UnitInventorySize
    UnitNatives.Item.Drop = UnitDropItemPoint
    UnitNatives.Item.MoveToSlot = UnitDropItemSlot
    UnitNatives.Item.MoveToTarget = UnitDropItemTarget
    UnitNatives.Item.Use = UnitUseItem
    UnitNatives.Item.UseOnPoint = UnitUseItemPoint
    UnitNatives.Item.UseOnTarget = UnitUseItemTarget

    UnitNatives.Ability.GetById = BlzGetUnitAbility
    UnitNatives.Ability.GetFromList = BlzGetUnitAbilityByIndex
    UnitNatives.Ability.Add = UnitAddAbility
    UnitNatives.Ability.Remove = UnitRemoveAbility
    UnitNatives.Ability.MakePermanent = UnitMakeAbilityPermanent
    UnitNatives.Ability.SetLevel = SetUnitAbilityLevel
    UnitNatives.Ability.IncreaseLevel = IncUnitAbilityLevel
    UnitNatives.Ability.DecreaseLevel = DecUnitAbilityLevel
    UnitNatives.Ability.GetLevel = GetUnitAbilityLevel
    UnitNatives.Ability.Hide = BlzUnitHideAbility
    UnitNatives.Ability.Disable = BlzUnitDisableAbility
    UnitNatives.Ability.SetCooldown = BlzSetUnitAbilityCooldown
    UnitNatives.Ability.GetCooldown = BlzGetUnitAbilityCooldown
    UnitNatives.Ability.GetRemainingCooldown = BlzGetUnitAbilityCooldownRemaining
    UnitNatives.Ability.StartCooldown = BlzStartUnitAbilityCooldown
    UnitNatives.Ability.EndCooldown = BlzEndUnitAbilityCooldown
    UnitNatives.Ability.SetManaCost = BlzSetUnitAbilityManaCost
    UnitNatives.Ability.GetManaCost = BlzGetUnitAbilityManaCost

    UnitNatives.Buff.RemoveBuffs = UnitRemoveBuffs
    UnitNatives.Buff.RemoveBuffsEx = UnitRemoveBuffsEx
    UnitNatives.Buff.HasBuffs = UnitHasBuffsEx
    UnitNatives.Buff.CountBuffs = UnitCountBuffsEx
    UnitNatives.Buff.Sleep = UnitAddSleep
    UnitNatives.Buff.CanSleep = UnitCanSleep
    UnitNatives.Buff.PermanentSleep = UnitAddSleepPerm
    UnitNatives.Buff.CanPermanentlySleep = UnitCanSleepPerm
    UnitNatives.Buff.IsSleeping = UnitIsSleeping
    UnitNatives.Buff.WakeUp = UnitWakeUp
    UnitNatives.Buff.ApplyTimedLife = UnitApplyTimedLife
    UnitNatives.Buff.PauseTimedLife = UnitPauseTimedLife
    UnitNatives.Buff.CancelTimedLife = BlzUnitCancelTimedLife

    UnitNatives.Building.SetConstructionProgress = UnitSetConstructionProgress
    UnitNatives.Building.SetUpgradeProgress = UnitSetUpgradeProgress

    UnitNatives.Building.GoldMine.SetResourceAmount = SetResourceAmount
    UnitNatives.Building.GoldMine.GetResourceAmount = GetResourceAmount
    UnitNatives.Building.GoldMine.AddResourceAmount = AddResourceAmount
    UnitNatives.Building.GoldMine.CreateBlighted = CreateBlightedGoldmine

    UnitNatives.Building.Waygate.SetDestination = WaygateSetDestination
    UnitNatives.Building.Waygate.GetDestinationX = WaygateGetDestinationX
    UnitNatives.Building.Waygate.GetDestinationY = WaygateGetDestinationY
    UnitNatives.Building.Waygate.Activate = WaygateActivate
    UnitNatives.Building.Waygate.IsActive = WaygateIsActive

    UnitNatives.Building.UnitShop.AddUnitToAllStock = AddUnitToAllStock
    UnitNatives.Building.UnitShop.AddUnitToStock = AddUnitToStock
    UnitNatives.Building.UnitShop.RemoveUnitFromAllStock = RemoveUnitFromAllStock
    UnitNatives.Building.UnitShop.RemoveUnitFromStock = RemoveUnitFromStock
    UnitNatives.Building.UnitShop.SetAmountOfCommandCardSlotsToUseGlobally = SetAllUnitTypeSlots
    UnitNatives.Building.UnitShop.SetAmountOfCommandCardSlotsToUse = SetUnitTypeSlots

    UnitNatives.Building.ItemShop.AddItemToAllStock = AddItemToAllStock
    UnitNatives.Building.ItemShop.AddItemToStock = AddItemToStock
    UnitNatives.Building.ItemShop.RemoveItemFromAllStock = RemoveItemFromAllStock
    UnitNatives.Building.ItemShop.RemoveItemFromStock = RemoveItemFromStock
    UnitNatives.Building.ItemShop.SetAmountOfCommandCardSlotsToUseGlobally = SetAllItemTypeSlots
    UnitNatives.Building.ItemShop.SetAmountOfCommandCardSlotsToUse = SetItemTypeSlots

    UnitNatives.Order.GetCurrent = GetUnitCurrentOrder
    UnitNatives.Order.Issue = IssueImmediateOrder
    UnitNatives.Order.IssueById = IssueImmediateOrderById
    UnitNatives.Order.IssueOnPoint = IssuePointOrder
    UnitNatives.Order.IssueOnPointById = IssuePointOrderById
    UnitNatives.Order.IssueAtLocation = IssuePointOrderLoc
    UnitNatives.Order.IssueAtLocationById = IssuePointOrderByIdLoc
    UnitNatives.Order.IssueAtTarget = IssueTargetOrder
    UnitNatives.Order.IssueAtTargetById = IssueTargetOrderById
    UnitNatives.Order.IssueInstantOnPoint = IssueInstantPointOrder
    UnitNatives.Order.IssueInstantOnPointById = IssueInstantPointOrderById
    UnitNatives.Order.IssueInstantAtTarget = IssueInstantTargetOrder
    UnitNatives.Order.IssueInstantAtTargetById = IssueInstantTargetOrderById
    UnitNatives.Order.IssueBuild = IssueBuildOrder
    UnitNatives.Order.IssueBuildById = IssueBuildOrderById
    UnitNatives.Order.QueueById = BlzQueueImmediateOrderById
    UnitNatives.Order.QueueOnPointById = BlzQueuePointOrderById
    UnitNatives.Order.QueueAtTargetById = BlzQueueTargetOrderById
    UnitNatives.Order.QueueInstantOnPointById = BlzQueueInstantPointOrderById
    UnitNatives.Order.QueueInstantAtTargetById = BlzQueueInstantTargetOrderById
    UnitNatives.Order.QueueBuildById = BlzQueueBuildOrderById
    UnitNatives.Order.QueueInstantOnPointById = BlzQueueInstantPointOrderById
    UnitNatives.Order.GetQueueCount = BlzGetUnitOrderCount
    UnitNatives.Order.QueueClear = BlzUnitClearOrders
    UnitNatives.Order.Stop = BlzUnitForceStopOrder

    UnitNatives.Order.NoAI.Issue = IssueNeutralImmediateOrder
    UnitNatives.Order.NoAI.IssueById = IssueNeutralImmediateOrderById
    UnitNatives.Order.NoAI.IssueOnPoint = IssueNeutralPointOrder
    UnitNatives.Order.NoAI.IssueOnPointById = IssueNeutralPointOrderById
    UnitNatives.Order.NoAI.IssueAtTarget = IssueNeutralTargetOrder
    UnitNatives.Order.NoAI.IssueAtTargetById = IssueNeutralTargetOrderById
    UnitNatives.Order.NoAI.QueueById = BlzQueueNeutralImmediateOrderById
    UnitNatives.Order.NoAI.QueueOnPointById = BlzQueueNeutralPointOrderById
    UnitNatives.Order.NoAI.QueueAtTargetById = BlzQueueNeutralTargetOrderById

    return UnitNatives
end)
if Debug then Debug.endFile() end
